---
- hosts: all
  vars:
    docker_users:
      - ubuntu
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.docker
    - geerlingguy.pip

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
